### ISSUE TITLE
Failing test scenarios

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#328]
Last night the following core test scenarios failed with encryption:

https://drone.owncloud.com/owncloud/encryption/2333/30/18
```
runsh: Total unexpected failed scenarios throughout the test run:

HTTP status code 500 is not the expected value 201
apiFederationToRoot1/federated.feature:285
apiFederationToRoot1/federated.feature:286

file '/PARENT/RandomFolder/file-to-share' should not exist. But it does exist and is a file
apiFederationToRoot2/federated.feature:178
apiFederationToRoot2/federated.feature:179
```

https://drone.owncloud.com/owncloud/encryption/2333/31/18
```
runsh: Total unexpected failed scenarios throughout the test run:

HTTP status code 500 is not the expected value 201
apiFederationToShares1/federated.feature:299
apiFederationToShares1/federated.feature:300

file '/PARENT/RandomFolder/file-to-share' should not exist. But it does exist and is a file
apiFederationToShares2/federated.feature:182
apiFederationToShares2/federated.feature:183
```

https://drone.owncloud.com/owncloud/encryption/2333/32/18
```
runsh: Total unexpected failed scenarios throughout the test run:

HTTP status code 500 is not the expected value 201
apiMain/external-storage.feature:38
```

https://drone.owncloud.com/owncloud/encryption/2333/110/18
```
file '/local_storage2/file-to-delete.txt' should not exist. But it does exist and is a file
runsh: Total unexpected failed scenarios throughout the test run:
cliLocalStorage/createLocalStorage.feature:13
cliLocalStorage/createLocalStorage.feature:30
cliLocalStorage/createLocalStorage.feature:39
cliLocalStorage/createLocalStorage.feature:47
cliLocalStorage/createLocalStorage.feature:55
cliLocalStorage/createLocalStorageForGroups.feature:13
cliLocalStorage/createLocalStorageForGroups.feature:28
cliLocalStorage/createLocalStorageForGroups.feature:40
cliLocalStorage/createLocalStorageForGroups.feature:58
cliLocalStorage/createLocalStorageForGroupsAndUsers.feature:13
cliLocalStorage/createLocalStorageForUsers.feature:14
cliLocalStorage/createLocalStorageForUsers.feature:39
cliLocalStorage/createLocalStorageForUsers.feature:61
cliLocalStorage/createLocalStorageForUsers.feature:71
cliLocalStorage/createLocalStorageForUsers.feature:81
cliLocalStorage/createLocalStorageOc10Issue36713.feature:14
cliLocalStorage/createLocalStorageOc10Issue36719.feature:13
cliLocalStorage/createLocalStorageOc10Issue36719.feature:30
cliLocalStorage/createLocalStorageOc10Issue36719.feature:51
cliLocalStorage/createLocalStorageReadOnly.feature:13
```

https://drone.owncloud.com/owncloud/encryption/2333/114/20
```
The downloaded content was expected to be 'this is a file in local storage', but actually is (500 error status)
runsh: Total unexpected failed scenarios throughout the test run:
webUIAdminSettings/adminStorageSettings.feature:17
webUIAdminSettings/adminStorageSettings.feature:34
```

Sample traceback from the log:
```
{"reqId":"SR18CrSLy139fMXjOHOh","level":3,"time":"2022-03-01T02:04:55+00:00","remoteAddr":"192.168.3.8","user":"Alice","app":"no app in context","method":"GET",
"url":"\/remote.php\/webdav\/local_storage1\/file-in-local-storage.txt",
"message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."}

{"reqId":"SR18CrSLy139fMXjOHOh","level":4,"time":"2022-03-01T02:04:55+00:00","remoteAddr":"192.168.3.8","user":"Alice","app":"webdav","method":"GET",
"url":"\/remote.php\/webdav\/local_storage1\/file-in-local-storage.txt",
"message":"Exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.: 
{\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",
\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",
\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(478): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n
#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(294): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n
#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read()\\n
#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(55): fread()\\n
#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(96): Icewind\\\\Streams\\\\Wrapper->stream_read()\\n
#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read()\\n
#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(112): stream_copy_to_stream()\\n
#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n
#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n
#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n
#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":374}"}
```

**Comment by phil-davis** [comment]
@jvillafanez these PRs were merged to core master on Monday 2022-02-28 and are related to encryption:
https://github.com/owncloud/core/pull/39822
https://github.com/owncloud/core/pull/39829

Do you think that there might be side-effects that are causing the above test fails?

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/39842 should fix the issue. I've checked only with a SMB storage, but I assume it's the same for the the federated shares since the previous code is pretty similar to the one in the PR. Still need to check though.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/2343/30/18
```
runsh: Total unexpected failed scenarios throughout the test run:
apiFederationToRoot1/federated.feature:285
apiFederationToRoot1/federated.feature:286
apiFederationToRoot2/federated.feature:178
apiFederationToRoot2/federated.feature:179
```

https://drone.owncloud.com/owncloud/encryption/2343/31/18
```
runsh: Total unexpected failed scenarios throughout the test run:
apiFederationToShares1/federated.feature:299
apiFederationToShares1/federated.feature:300
apiFederationToShares2/federated.feature:182
apiFederationToShares2/federated.feature:183
```

those are still failing.

@jvillafanez

**Comment by jvillafanez** [comment]
I'm having trouble to reproduce the failing tests.
Manually, the tests pass unless I'm doing something different (the tests are difficult to follow, so maybe I'm missing something)
I've also tried to run the test suite, but I'm getting different errors:
```
  Scenario Outline: Overwrite a federated shared file as recipient using old chunking                                        # /var/www/owncloud/tests/acceptance/features/apiFederationToShares1/federated.feature:282
    Given using server "REMOTE"                                                                                              # FeatureContext::usingServer()
    And user "Alice" has uploaded file "filesForUpload/textfile.txt" to "textfile0.txt"                                      # FeatureContext::userHasUploadedAFileTo()
    And user "Alice" from server "REMOTE" has shared "/textfile0.txt" with user "Brian" from server "LOCAL"                  # FederationContext::userFromServerHasSharedWithUserFromServer()
    And user "Brian" from server "LOCAL" has accepted the last pending share                                                 # FederationContext::userFromServerHasAcceptedLastPendingShare()
    And using server "LOCAL"                                                                                                 # FeatureContext::usingServer()
    And using OCS API version "<ocs-api-version>"                                                                            # FeatureContext::usingOcsApiVersion()
    When user "Brian" uploads the following "3" chunks to "/Shares/textfile0.txt" with old chunking and using the WebDAV API # FeatureContext::userUploadsTheFollowingTotalChunksUsingOldChunking()
      | number | content |
      | 1      | AAAAA   |
      | 2      | BBBBB   |
      | 3      | CCCCC   |
    Then the HTTP status code should be "201"                                                                                # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the content of file "/Shares/textfile0.txt" for user "Brian" should be "AAAAABBBBBCCCCC"                             # FeatureContext::contentOfFileForUserShouldBe()
    And the content of file "/textfile0.txt" for user "Alice" on server "REMOTE" should be "AAAAABBBBBCCCCC"                 # FeatureContext::theContentOfFileForUserOnServerShouldBe()

    Examples:
      | ocs-api-version | ocs-status |
      ┌─ @BeforeScenario # FeatureContext::prepareParametersBeforeScenario()
      │
      ╳  TestHelpers\AppConfigHelper::modifyAppConfigs expected HTTP status 200 but got 404
      ╳  Failed asserting that 404 matches expected 200.
      │
      ┌─ @BeforeScenario @federation-app-required # FeatureContext::setInitialTrustedServersBeforeScenario()
      │
      ╳  Could not get the list of trusted servers<!doctype html><html><head><title>404 Not Found</title><style>
      ╳  body { background-color: #fcfcfc; color: #333333; margin: 0; padding:0; }
      ╳  h1 { font-size: 1.5em; font-weight: normal; background-color: #9999cc; min-height:2em; line-height:2em; border-bottom: 1px inset black; margin: 0; }
      ╳  h1, p { padding-left: 10px; }
      ╳  code.url { background-color: #eeeeee; font-family:monospace; padding:0 2px;}
      ╳  </style>
      ╳  </head><body><h1>Not Found</h1><p>The requested resource <code class="url">/ocs/v2.php/apps/testing/api/v1/trustedservers</code> was not found on this server.</p></body></html> (Exception)
      │
      ┌─ @BeforeScenario # FeatureContext::rememberAppEnabledDisabledState()
      │
      ╳  Warning: simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in /var/www/owncloud/tests/TestHelpers/SetupHelper.php line 917
      │
      ┌─ @BeforeScenario # OccContext::before()
      │
      ╳  Warning: simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in /var/www/owncloud/tests/TestHelpers/SetupHelper.php line 917
      │
      | 1               | 100        |
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34984 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34984 [200]: POST /ocs/v1.php/apps/testing/api/v1/apps
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34984 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34988 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34988 [200]: POST /ocs/v2.php/apps/testing/api/v1/occ
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34988 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34994 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34994 [200]: DELETE /ocs/v2.php/apps/testing/api/v1/opcache
[Mon Mar 14 13:17:42 2022] 127.0.0.1:34994 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44012 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44012 [404]: (null) /ocs/v1.php/apps/testing/api/v1/apps - No such file or directory
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44012 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:35000 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:35000 [200]: GET /ocs/v2.php/apps/testing/api/v1/trustedservers
[Mon Mar 14 13:17:42 2022] 127.0.0.1:35000 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44018 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44018 [404]: (null) /ocs/v2.php/apps/testing/api/v1/trustedservers - No such file or directory
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44018 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44020 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44020 [404]: (null) /ocs/v2.php/apps/testing/api/v1/occ - No such file or directory
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44020 Closing
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44022 Accepted
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44022 [404]: (null) /ocs/v2.php/apps/testing/api/v1/occ - No such file or directory
[Mon Mar 14 13:17:42 2022] 127.0.0.1:44022 Closing
      ┌─ @BeforeScenario # FeatureContext::prepareParametersBeforeScenario()
      │
      ╳  TestHelpers\AppConfigHelper::modifyAppConfigs expected HTTP status 200 but got 404
      ╳  Failed asserting that 404 matches expected 200.
      │
      ┌─ @BeforeScenario @federation-app-required # FeatureContext::setInitialTrustedServersBeforeScenario()
      │
      ╳  Could not get the list of trusted servers<!doctype html><html><head><title>404 Not Found</title><style>
      ╳  body { background-color: #fcfcfc; color: #333333; margin: 0; padding:0; }
      ╳  h1 { font-size: 1.5em; font-weight: normal; background-color: #9999cc; min-height:2em; line-height:2em; border-bottom: 1px inset black; margin: 0; }
      ╳  h1, p { padding-left: 10px; }
      ╳  code.url { background-color: #eeeeee; font-family:monospace; padding:0 2px;}
      ╳  </style>
      ╳  </head><body><h1>Not Found</h1><p>The requested resource <code class="url">/ocs/v2.php/apps/testing/api/v1/trustedservers</code> was not found on this server.</p></body></html> (Exception)
      │
      ┌─ @BeforeScenario # FeatureContext::rememberAppEnabledDisabledState()
      │
      ╳  Warning: simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in /var/www/owncloud/tests/TestHelpers/SetupHelper.php line 917
      │
      ┌─ @BeforeScenario # OccContext::before()
      │
      ╳  Warning: simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in /var/www/owncloud/tests/TestHelpers/SetupHelper.php line 917
      │
      | 2               | 200        |

--- Skipped scenarios:

    /var/www/owncloud/tests/acceptance/features/apiFederationToShares1/federated.feature:299
    /var/www/owncloud/tests/acceptance/features/apiFederationToShares1/federated.feature:300

2 scenarios (2 skipped)
36 steps (36 skipped)
0m1.39s (16.81Mb)

```

**Comment by jvillafanez** [comment]
I think I know what's happening. The problem is more complex.

Assuming user1 receives a remote share, and the server (where user1 is) is encrypted, the problem is that the owner of the remote share isn't present in the local share. `userRemote@server.remote.com` doesn't exists in the local server.
This means that the keys we're supposed to move don't exists. In addition, the keys would be in the remote server.

Previously, it was assumed that the keys were under the user1's account, the keys movement likely fails, and new keys are generated (we might need to confirm this). We might be able to recover this behavior for remote shares, although conceptually it seems wrong.

**Comment by jvillafanez** [comment]
I'm trying the following scenario:
1. Assuming the local server has master encryption enabled and the remote one doesn't have any encryption
2. Remote userR creates "/parent/folder/subfolder/test-file.txt"
3. Remote userR shares "/parent/folder" to userL@localserver (userL belongs to a local server, not remote one)
4. Local userL deletes "/folder/subfolder/test-file.txt" (shared from the remote server)

With the planned changes to revert the behavior for the remote shares, I'm having the following error:
```
{"reqId":"TV7zTFQCHwh4MeRnqGOm","level":3,"time":"2022-03-15T12:10:57+00:00","remoteAddr":"10.0.2.27","user":"admin","app":"PHP","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/folder\/subfolder","message":"call_user_func_array() expects parameter 1 to be a valid callback, class 'OCA\\Files_Sharing\\External\\Storage' does not have a method 'copyKeys' at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php#511"}
```

As far as I know, the changes we've made so far are limited to the the `getUidAndFilename` function (https://github.com/owncloud/core/blob/c3e6aef20c57b3dd6f5cb361cf9b904eada0f201/lib/private/Encryption/Util.php#L230), so it seems weird that the code was working before through that scenario.

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/39892 brings back the previous behavior for remote shares with encryption. It should fix the failing tests since the behavior is the same as it was previously.

In any case, the scenario described in https://github.com/owncloud/encryption/issues/328#issuecomment-1067932520 is still broken. As said, there are conceptual and architectural problems that require deep changes in the code. It doesn't seem possible to fix without breaking things apart.

**Comment by phil-davis** [comment]
All these tests passed in the CI run last night: https://drone.owncloud.com/owncloud/encryption/2362

The recent changes in core have fixed all these tests - closing.
